http:
  middlewares:
    # A recommended middleware for security, tells browsers to only use HTTPS
    hsts:
      headers:
        # 31536000 seconds = 1 year. This is required for HSTS preloading.
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true

    # A recommended middleware for performance, enables gzip compression
    compress:
      compress: {}

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      sniStrict: true
