http:
  middlewares:
    auth:
      basicAuth:
        users:
          - '{{ env "AUTH_USER" }}:{{ env "AUTH_PASS_HASH" }}'

    adguard-strip:
      stripPrefix:
        prefixes:
          - /adguard

    # A recommended middleware for security, tells browsers to only use HTTPS
    hsts:
      headers:
        # 31536000 seconds = 1 year. This is required for HSTS preloading.
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true

    # A recommended middleware for performance, enables gzip compression
    compress:
      compress: {}

  routers:
    # Traefik dashboard - higher priority for specific path
    traefik:
      rule: Host(`{{ env "DOMAIN" }}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      entryPoints:
        - websecure
      middlewares:
        - auth
      service: api@internal

    # AdGuard Home - higher priority for specific path
    adguard:
      rule: Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/adguard`)
      entryPoints:
        - websecure
      middlewares:
        - auth
        - adguard-strip
      service: adguard@docker

    # WireGuard web UI - root path with lowest priority
    wg-easy:
      rule: Host(`{{ env "DOMAIN" }}`)
      entryPoints:
        - websecure
      middlewares:
        - auth
      service: wg-easy@docker
      priority: 1

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      sniStrict: true
