global:
  sendAnonymousUsage: false

log:
  level: INFO

entryPoints:
  web:
    address: ":80/tcp"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443/tcp"
    http:
      middlewares:
        - compress@file # Global compression for performance
        - hsts@file # Global HSTS headers for security
      tls:
        certResolver: letsencrypt
    http3: {}

api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /acme.json
      httpChallenge:
        entryPoint: web

providers:
  # Docker provider to auto-discover services from container labels
  docker:
    watch: true
    network: traefik-net
    exposedByDefault: false

  file:
    filename: /traefik_dynamic.yml
# serversTransport:
#     insecureSkipVerify: true
