global:
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true

entryPoints:
  web:
    address: ":80/tcp"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443/tcp"
    http:
      middlewares:
        - auth@file # Global authentication
        - hsts@file # Global HSTS headers for security
        - compress@file # Global compression for performance
      tls:
        certResolver: letsencrypt
        options: default@file
    http3: {}

providers:
  # Docker provider to auto-discover services from container labels
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

  # File provider to load routing rules and middlewares from a separate file
  file:
    filename: traefik_dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${TRAEFIK_ACME_EMAIL}
      storage: acme.json
      httpChallenge:
        entryPoint: web
