global:
  sendAnonymousUsage: false

log:
  level: INFO

entryPoints:
  web:
    address: ":80/tcp"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443/tcp"
    http:
      middlewares:
        - compress@file # Global compression for performance
        - hsts@file # Global HSTS headers for security
      tls:
        certResolver: letsencrypt
    http3: {}

api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      storage: acme.json
      httpChallenge:
        entryPoint: web

providers:
  # Docker provider to auto-discover services from container labels
  docker:
    exposedByDefault: false
    watch: true
    network: traefik-net

  # File provider to load routing rules and middlewares from a separate file
  file:
    filename: traefik_dynamic.yml
    watch: true
